# Generated by Django 3.0.1 on 2020-01-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('img_url', models.CharField(max_length=2048)),
                ('clade', models.CharField(max_length=120)),
                ('meaning', models.CharField(max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.CharField(default='https://gw.alipayobjects.com/zos/rmsportal/mqaQswcyDLcXyDKnZfES.png', max_length=2048),
        ),
    ]
